
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'BlocksLogo': typeof import("../../app/components/blocks/logo.vue").default
  'MenusFooterNav': typeof import("../../app/components/menus/FooterNav.vue").default
  'MenusEcosystemmenu': typeof import("../../app/components/menus/ecosystemmenu.vue").default
  'MenusLayoutNotifications': typeof import("../../app/components/menus/layoutNotifications.vue").default
  'MenusLowernav': typeof import("../../app/components/menus/lowernav.vue").default
  'MenusMobilesearch': typeof import("../../app/components/menus/mobilesearch.vue").default
  'MenusSidebarnav': typeof import("../../app/components/menus/sidebarnav.vue").default
  'MenusTopmenu': typeof import("../../app/components/menus/topmenu.vue").default
  'RelatedArticle': typeof import("../../app/components/related/article.vue").default
  'RelatedRelatedposts': typeof import("../../app/components/related/relatedposts.vue").default
  'RelatedRelatedproducts': typeof import("../../app/components/related/relatedproducts.vue").default
  'RelatedTopics': typeof import("../../app/components/related/topics.vue").default
  'Search': typeof import("../../app/components/search/search.vue").default
  'AuthState': typeof import("../../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
  'SfAccordionItem': typeof import("@storefront-ui/vue").SfAccordionItem
  'SfBadge': typeof import("@storefront-ui/vue").SfBadge
  'SfButton': typeof import("@storefront-ui/vue").SfButton
  'SfCheckbox': typeof import("@storefront-ui/vue").SfCheckbox
  'SfChip': typeof import("@storefront-ui/vue").SfChip
  'SfCounter': typeof import("@storefront-ui/vue").SfCounter
  'SfDrawer': typeof import("@storefront-ui/vue").SfDrawer
  'SfDropdown': typeof import("@storefront-ui/vue").SfDropdown
  'SfIconAdd': typeof import("@storefront-ui/vue").SfIconAdd
  'SfIconAddShoppingCart': typeof import("@storefront-ui/vue").SfIconAddShoppingCart
  'SfIconAlokai': typeof import("@storefront-ui/vue").SfIconAlokai
  'SfIconAlokaiFull': typeof import("@storefront-ui/vue").SfIconAlokaiFull
  'SfIconArrowBack': typeof import("@storefront-ui/vue").SfIconArrowBack
  'SfIconArrowDownward': typeof import("@storefront-ui/vue").SfIconArrowDownward
  'SfIconArrowForward': typeof import("@storefront-ui/vue").SfIconArrowForward
  'SfIconArrowUpward': typeof import("@storefront-ui/vue").SfIconArrowUpward
  'SfIconBase': typeof import("@storefront-ui/vue").SfIconBase
  'SfIconBlock': typeof import("@storefront-ui/vue").SfIconBlock
  'SfIconCalendarToday': typeof import("@storefront-ui/vue").SfIconCalendarToday
  'SfIconCall': typeof import("@storefront-ui/vue").SfIconCall
  'SfIconCancel': typeof import("@storefront-ui/vue").SfIconCancel
  'SfIconCheck': typeof import("@storefront-ui/vue").SfIconCheck
  'SfIconCheckBox': typeof import("@storefront-ui/vue").SfIconCheckBox
  'SfIconCheckBoxOutlineBlank': typeof import("@storefront-ui/vue").SfIconCheckBoxOutlineBlank
  'SfIconCheckCircle': typeof import("@storefront-ui/vue").SfIconCheckCircle
  'SfIconChevronLeft': typeof import("@storefront-ui/vue").SfIconChevronLeft
  'SfIconChevronRight': typeof import("@storefront-ui/vue").SfIconChevronRight
  'SfIconCircle': typeof import("@storefront-ui/vue").SfIconCircle
  'SfIconClose': typeof import("@storefront-ui/vue").SfIconClose
  'SfIconCloseSm': typeof import("@storefront-ui/vue").SfIconCloseSm
  'SfIconCompareArrows': typeof import("@storefront-ui/vue").SfIconCompareArrows
  'SfIconContactSupport': typeof import("@storefront-ui/vue").SfIconContactSupport
  'SfIconCreditCard': typeof import("@storefront-ui/vue").SfIconCreditCard
  'SfIconDelete': typeof import("@storefront-ui/vue").SfIconDelete
  'SfIconDownload': typeof import("@storefront-ui/vue").SfIconDownload
  'SfIconEmail': typeof import("@storefront-ui/vue").SfIconEmail
  'SfIconError': typeof import("@storefront-ui/vue").SfIconError
  'SfIconExpandLess': typeof import("@storefront-ui/vue").SfIconExpandLess
  'SfIconExpandMore': typeof import("@storefront-ui/vue").SfIconExpandMore
  'SfIconFacebook': typeof import("@storefront-ui/vue").SfIconFacebook
  'SfIconFavorite': typeof import("@storefront-ui/vue").SfIconFavorite
  'SfIconFavoriteFilled': typeof import("@storefront-ui/vue").SfIconFavoriteFilled
  'SfIconGridView': typeof import("@storefront-ui/vue").SfIconGridView
  'SfIconHelp': typeof import("@storefront-ui/vue").SfIconHelp
  'SfIconHome': typeof import("@storefront-ui/vue").SfIconHome
  'SfIconIndeterminateCheckBox': typeof import("@storefront-ui/vue").SfIconIndeterminateCheckBox
  'SfIconInfo': typeof import("@storefront-ui/vue").SfIconInfo
  'SfIconInstagram': typeof import("@storefront-ui/vue").SfIconInstagram
  'SfIconLanguage': typeof import("@storefront-ui/vue").SfIconLanguage
  'SfIconLocalShipping': typeof import("@storefront-ui/vue").SfIconLocalShipping
  'SfIconLocalFireDepartment': typeof import("@storefront-ui/vue").SfIconLocal_fire_department
  'SfIconLocationOn': typeof import("@storefront-ui/vue").SfIconLocationOn
  'SfIconLocationOnFilled': typeof import("@storefront-ui/vue").SfIconLocationOnFilled
  'SfIconLock': typeof import("@storefront-ui/vue").SfIconLock
  'SfIconLockOpen': typeof import("@storefront-ui/vue").SfIconLockOpen
  'SfIconLogin': typeof import("@storefront-ui/vue").SfIconLogin
  'SfIconLogout': typeof import("@storefront-ui/vue").SfIconLogout
  'SfIconMenu': typeof import("@storefront-ui/vue").SfIconMenu
  'SfIconMoreHoriz': typeof import("@storefront-ui/vue").SfIconMoreHoriz
  'SfIconMoreVert': typeof import("@storefront-ui/vue").SfIconMoreVert
  'SfIconOpenInNew': typeof import("@storefront-ui/vue").SfIconOpenInNew
  'SfIconOpenSource': typeof import("@storefront-ui/vue").SfIconOpenSource
  'SfIconPackage': typeof import("@storefront-ui/vue").SfIconPackage
  'SfIconPercent': typeof import("@storefront-ui/vue").SfIconPercent
  'SfIconPerson': typeof import("@storefront-ui/vue").SfIconPerson
  'SfIconPinterest': typeof import("@storefront-ui/vue").SfIconPinterest
  'SfIconPublishedWithChanges': typeof import("@storefront-ui/vue").SfIconPublishedWithChanges
  'SfIconRadioButtonChecked': typeof import("@storefront-ui/vue").SfIconRadioButtonChecked
  'SfIconRadioButtonUnchecked': typeof import("@storefront-ui/vue").SfIconRadioButtonUnchecked
  'SfIconReact': typeof import("@storefront-ui/vue").SfIconReact
  'SfIconRemove': typeof import("@storefront-ui/vue").SfIconRemove
  'SfIconRemoveShoppingCart': typeof import("@storefront-ui/vue").SfIconRemoveShoppingCart
  'SfIconSafetyCheck': typeof import("@storefront-ui/vue").SfIconSafetyCheck
  'SfIconSchedule': typeof import("@storefront-ui/vue").SfIconSchedule
  'SfIconSearch': typeof import("@storefront-ui/vue").SfIconSearch
  'SfIconSell': typeof import("@storefront-ui/vue").SfIconSell
  'SfIconShare': typeof import("@storefront-ui/vue").SfIconShare
  'SfIconShoppingCart': typeof import("@storefront-ui/vue").SfIconShoppingCart
  'SfIconShoppingCartCheckout': typeof import("@storefront-ui/vue").SfIconShoppingCartCheckout
  'SfIconSort': typeof import("@storefront-ui/vue").SfIconSort
  'SfIconStar': typeof import("@storefront-ui/vue").SfIconStar
  'SfIconStarFilled': typeof import("@storefront-ui/vue").SfIconStarFilled
  'SfIconStarHalf': typeof import("@storefront-ui/vue").SfIconStarHalf
  'SfIconThumbDown': typeof import("@storefront-ui/vue").SfIconThumbDown
  'SfIconThumbUp': typeof import("@storefront-ui/vue").SfIconThumbUp
  'SfIconTune': typeof import("@storefront-ui/vue").SfIconTune
  'SfIconTwitter': typeof import("@storefront-ui/vue").SfIconTwitter
  'SfIconUndo': typeof import("@storefront-ui/vue").SfIconUndo
  'SfIconUnfoldMore': typeof import("@storefront-ui/vue").SfIconUnfoldMore
  'SfIconUpload': typeof import("@storefront-ui/vue").SfIconUpload
  'SfIconViewList': typeof import("@storefront-ui/vue").SfIconViewList
  'SfIconVisibility': typeof import("@storefront-ui/vue").SfIconVisibility
  'SfIconVisibilityOff': typeof import("@storefront-ui/vue").SfIconVisibilityOff
  'SfIconVsfDiamond': typeof import("@storefront-ui/vue").SfIconVsfDiamond
  'SfIconVuejs': typeof import("@storefront-ui/vue").SfIconVuejs
  'SfIconVuestorefront': typeof import("@storefront-ui/vue").SfIconVuestorefront
  'SfIconWarehouse': typeof import("@storefront-ui/vue").SfIconWarehouse
  'SfIconWarning': typeof import("@storefront-ui/vue").SfIconWarning
  'SfIconYoutube': typeof import("@storefront-ui/vue").SfIconYoutube
  'SfInput': typeof import("@storefront-ui/vue").SfInput
  'SfLink': typeof import("@storefront-ui/vue").SfLink
  'SfListItem': typeof import("@storefront-ui/vue").SfListItem
  'SfLoaderCircular': typeof import("@storefront-ui/vue").SfLoaderCircular
  'SfLoaderLinear': typeof import("@storefront-ui/vue").SfLoaderLinear
  'SfModal': typeof import("@storefront-ui/vue").SfModal
  'SfProgressCircular': typeof import("@storefront-ui/vue").SfProgressCircular
  'SfProgressLinear': typeof import("@storefront-ui/vue").SfProgressLinear
  'SfRadio': typeof import("@storefront-ui/vue").SfRadio
  'SfRating': typeof import("@storefront-ui/vue").SfRating
  'SfRatingButton': typeof import("@storefront-ui/vue").SfRatingButton
  'SfScrollable': typeof import("@storefront-ui/vue").SfScrollable
  'SfSelect': typeof import("@storefront-ui/vue").SfSelect
  'SfSwitch': typeof import("@storefront-ui/vue").SfSwitch
  'SfTextarea': typeof import("@storefront-ui/vue").SfTextarea
  'SfThumbnail': typeof import("@storefront-ui/vue").SfThumbnail
  'SfTooltip': typeof import("@storefront-ui/vue").SfTooltip
  'NuxtLinkLocale': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
  'SwitchLocalePathLink': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
  'TiptapEditorContent': typeof import("@tiptap/vue-3").EditorContent
  'TiptapFloatingMenu': typeof import("@tiptap/vue-3/menus").FloatingMenu
  'TiptapBubbleMenu': typeof import("@tiptap/vue-3/menus").BubbleMenu
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyBlocksLogo': LazyComponent<typeof import("../../app/components/blocks/logo.vue").default>
  'LazyMenusFooterNav': LazyComponent<typeof import("../../app/components/menus/FooterNav.vue").default>
  'LazyMenusEcosystemmenu': LazyComponent<typeof import("../../app/components/menus/ecosystemmenu.vue").default>
  'LazyMenusLayoutNotifications': LazyComponent<typeof import("../../app/components/menus/layoutNotifications.vue").default>
  'LazyMenusLowernav': LazyComponent<typeof import("../../app/components/menus/lowernav.vue").default>
  'LazyMenusMobilesearch': LazyComponent<typeof import("../../app/components/menus/mobilesearch.vue").default>
  'LazyMenusSidebarnav': LazyComponent<typeof import("../../app/components/menus/sidebarnav.vue").default>
  'LazyMenusTopmenu': LazyComponent<typeof import("../../app/components/menus/topmenu.vue").default>
  'LazyRelatedArticle': LazyComponent<typeof import("../../app/components/related/article.vue").default>
  'LazyRelatedRelatedposts': LazyComponent<typeof import("../../app/components/related/relatedposts.vue").default>
  'LazyRelatedRelatedproducts': LazyComponent<typeof import("../../app/components/related/relatedproducts.vue").default>
  'LazyRelatedTopics': LazyComponent<typeof import("../../app/components/related/topics.vue").default>
  'LazySearch': LazyComponent<typeof import("../../app/components/search/search.vue").default>
  'LazyAuthState': LazyComponent<typeof import("../../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
  'LazySfAccordionItem': LazyComponent<typeof import("@storefront-ui/vue").SfAccordionItem>
  'LazySfBadge': LazyComponent<typeof import("@storefront-ui/vue").SfBadge>
  'LazySfButton': LazyComponent<typeof import("@storefront-ui/vue").SfButton>
  'LazySfCheckbox': LazyComponent<typeof import("@storefront-ui/vue").SfCheckbox>
  'LazySfChip': LazyComponent<typeof import("@storefront-ui/vue").SfChip>
  'LazySfCounter': LazyComponent<typeof import("@storefront-ui/vue").SfCounter>
  'LazySfDrawer': LazyComponent<typeof import("@storefront-ui/vue").SfDrawer>
  'LazySfDropdown': LazyComponent<typeof import("@storefront-ui/vue").SfDropdown>
  'LazySfIconAdd': LazyComponent<typeof import("@storefront-ui/vue").SfIconAdd>
  'LazySfIconAddShoppingCart': LazyComponent<typeof import("@storefront-ui/vue").SfIconAddShoppingCart>
  'LazySfIconAlokai': LazyComponent<typeof import("@storefront-ui/vue").SfIconAlokai>
  'LazySfIconAlokaiFull': LazyComponent<typeof import("@storefront-ui/vue").SfIconAlokaiFull>
  'LazySfIconArrowBack': LazyComponent<typeof import("@storefront-ui/vue").SfIconArrowBack>
  'LazySfIconArrowDownward': LazyComponent<typeof import("@storefront-ui/vue").SfIconArrowDownward>
  'LazySfIconArrowForward': LazyComponent<typeof import("@storefront-ui/vue").SfIconArrowForward>
  'LazySfIconArrowUpward': LazyComponent<typeof import("@storefront-ui/vue").SfIconArrowUpward>
  'LazySfIconBase': LazyComponent<typeof import("@storefront-ui/vue").SfIconBase>
  'LazySfIconBlock': LazyComponent<typeof import("@storefront-ui/vue").SfIconBlock>
  'LazySfIconCalendarToday': LazyComponent<typeof import("@storefront-ui/vue").SfIconCalendarToday>
  'LazySfIconCall': LazyComponent<typeof import("@storefront-ui/vue").SfIconCall>
  'LazySfIconCancel': LazyComponent<typeof import("@storefront-ui/vue").SfIconCancel>
  'LazySfIconCheck': LazyComponent<typeof import("@storefront-ui/vue").SfIconCheck>
  'LazySfIconCheckBox': LazyComponent<typeof import("@storefront-ui/vue").SfIconCheckBox>
  'LazySfIconCheckBoxOutlineBlank': LazyComponent<typeof import("@storefront-ui/vue").SfIconCheckBoxOutlineBlank>
  'LazySfIconCheckCircle': LazyComponent<typeof import("@storefront-ui/vue").SfIconCheckCircle>
  'LazySfIconChevronLeft': LazyComponent<typeof import("@storefront-ui/vue").SfIconChevronLeft>
  'LazySfIconChevronRight': LazyComponent<typeof import("@storefront-ui/vue").SfIconChevronRight>
  'LazySfIconCircle': LazyComponent<typeof import("@storefront-ui/vue").SfIconCircle>
  'LazySfIconClose': LazyComponent<typeof import("@storefront-ui/vue").SfIconClose>
  'LazySfIconCloseSm': LazyComponent<typeof import("@storefront-ui/vue").SfIconCloseSm>
  'LazySfIconCompareArrows': LazyComponent<typeof import("@storefront-ui/vue").SfIconCompareArrows>
  'LazySfIconContactSupport': LazyComponent<typeof import("@storefront-ui/vue").SfIconContactSupport>
  'LazySfIconCreditCard': LazyComponent<typeof import("@storefront-ui/vue").SfIconCreditCard>
  'LazySfIconDelete': LazyComponent<typeof import("@storefront-ui/vue").SfIconDelete>
  'LazySfIconDownload': LazyComponent<typeof import("@storefront-ui/vue").SfIconDownload>
  'LazySfIconEmail': LazyComponent<typeof import("@storefront-ui/vue").SfIconEmail>
  'LazySfIconError': LazyComponent<typeof import("@storefront-ui/vue").SfIconError>
  'LazySfIconExpandLess': LazyComponent<typeof import("@storefront-ui/vue").SfIconExpandLess>
  'LazySfIconExpandMore': LazyComponent<typeof import("@storefront-ui/vue").SfIconExpandMore>
  'LazySfIconFacebook': LazyComponent<typeof import("@storefront-ui/vue").SfIconFacebook>
  'LazySfIconFavorite': LazyComponent<typeof import("@storefront-ui/vue").SfIconFavorite>
  'LazySfIconFavoriteFilled': LazyComponent<typeof import("@storefront-ui/vue").SfIconFavoriteFilled>
  'LazySfIconGridView': LazyComponent<typeof import("@storefront-ui/vue").SfIconGridView>
  'LazySfIconHelp': LazyComponent<typeof import("@storefront-ui/vue").SfIconHelp>
  'LazySfIconHome': LazyComponent<typeof import("@storefront-ui/vue").SfIconHome>
  'LazySfIconIndeterminateCheckBox': LazyComponent<typeof import("@storefront-ui/vue").SfIconIndeterminateCheckBox>
  'LazySfIconInfo': LazyComponent<typeof import("@storefront-ui/vue").SfIconInfo>
  'LazySfIconInstagram': LazyComponent<typeof import("@storefront-ui/vue").SfIconInstagram>
  'LazySfIconLanguage': LazyComponent<typeof import("@storefront-ui/vue").SfIconLanguage>
  'LazySfIconLocalShipping': LazyComponent<typeof import("@storefront-ui/vue").SfIconLocalShipping>
  'LazySfIconLocalFireDepartment': LazyComponent<typeof import("@storefront-ui/vue").SfIconLocal_fire_department>
  'LazySfIconLocationOn': LazyComponent<typeof import("@storefront-ui/vue").SfIconLocationOn>
  'LazySfIconLocationOnFilled': LazyComponent<typeof import("@storefront-ui/vue").SfIconLocationOnFilled>
  'LazySfIconLock': LazyComponent<typeof import("@storefront-ui/vue").SfIconLock>
  'LazySfIconLockOpen': LazyComponent<typeof import("@storefront-ui/vue").SfIconLockOpen>
  'LazySfIconLogin': LazyComponent<typeof import("@storefront-ui/vue").SfIconLogin>
  'LazySfIconLogout': LazyComponent<typeof import("@storefront-ui/vue").SfIconLogout>
  'LazySfIconMenu': LazyComponent<typeof import("@storefront-ui/vue").SfIconMenu>
  'LazySfIconMoreHoriz': LazyComponent<typeof import("@storefront-ui/vue").SfIconMoreHoriz>
  'LazySfIconMoreVert': LazyComponent<typeof import("@storefront-ui/vue").SfIconMoreVert>
  'LazySfIconOpenInNew': LazyComponent<typeof import("@storefront-ui/vue").SfIconOpenInNew>
  'LazySfIconOpenSource': LazyComponent<typeof import("@storefront-ui/vue").SfIconOpenSource>
  'LazySfIconPackage': LazyComponent<typeof import("@storefront-ui/vue").SfIconPackage>
  'LazySfIconPercent': LazyComponent<typeof import("@storefront-ui/vue").SfIconPercent>
  'LazySfIconPerson': LazyComponent<typeof import("@storefront-ui/vue").SfIconPerson>
  'LazySfIconPinterest': LazyComponent<typeof import("@storefront-ui/vue").SfIconPinterest>
  'LazySfIconPublishedWithChanges': LazyComponent<typeof import("@storefront-ui/vue").SfIconPublishedWithChanges>
  'LazySfIconRadioButtonChecked': LazyComponent<typeof import("@storefront-ui/vue").SfIconRadioButtonChecked>
  'LazySfIconRadioButtonUnchecked': LazyComponent<typeof import("@storefront-ui/vue").SfIconRadioButtonUnchecked>
  'LazySfIconReact': LazyComponent<typeof import("@storefront-ui/vue").SfIconReact>
  'LazySfIconRemove': LazyComponent<typeof import("@storefront-ui/vue").SfIconRemove>
  'LazySfIconRemoveShoppingCart': LazyComponent<typeof import("@storefront-ui/vue").SfIconRemoveShoppingCart>
  'LazySfIconSafetyCheck': LazyComponent<typeof import("@storefront-ui/vue").SfIconSafetyCheck>
  'LazySfIconSchedule': LazyComponent<typeof import("@storefront-ui/vue").SfIconSchedule>
  'LazySfIconSearch': LazyComponent<typeof import("@storefront-ui/vue").SfIconSearch>
  'LazySfIconSell': LazyComponent<typeof import("@storefront-ui/vue").SfIconSell>
  'LazySfIconShare': LazyComponent<typeof import("@storefront-ui/vue").SfIconShare>
  'LazySfIconShoppingCart': LazyComponent<typeof import("@storefront-ui/vue").SfIconShoppingCart>
  'LazySfIconShoppingCartCheckout': LazyComponent<typeof import("@storefront-ui/vue").SfIconShoppingCartCheckout>
  'LazySfIconSort': LazyComponent<typeof import("@storefront-ui/vue").SfIconSort>
  'LazySfIconStar': LazyComponent<typeof import("@storefront-ui/vue").SfIconStar>
  'LazySfIconStarFilled': LazyComponent<typeof import("@storefront-ui/vue").SfIconStarFilled>
  'LazySfIconStarHalf': LazyComponent<typeof import("@storefront-ui/vue").SfIconStarHalf>
  'LazySfIconThumbDown': LazyComponent<typeof import("@storefront-ui/vue").SfIconThumbDown>
  'LazySfIconThumbUp': LazyComponent<typeof import("@storefront-ui/vue").SfIconThumbUp>
  'LazySfIconTune': LazyComponent<typeof import("@storefront-ui/vue").SfIconTune>
  'LazySfIconTwitter': LazyComponent<typeof import("@storefront-ui/vue").SfIconTwitter>
  'LazySfIconUndo': LazyComponent<typeof import("@storefront-ui/vue").SfIconUndo>
  'LazySfIconUnfoldMore': LazyComponent<typeof import("@storefront-ui/vue").SfIconUnfoldMore>
  'LazySfIconUpload': LazyComponent<typeof import("@storefront-ui/vue").SfIconUpload>
  'LazySfIconViewList': LazyComponent<typeof import("@storefront-ui/vue").SfIconViewList>
  'LazySfIconVisibility': LazyComponent<typeof import("@storefront-ui/vue").SfIconVisibility>
  'LazySfIconVisibilityOff': LazyComponent<typeof import("@storefront-ui/vue").SfIconVisibilityOff>
  'LazySfIconVsfDiamond': LazyComponent<typeof import("@storefront-ui/vue").SfIconVsfDiamond>
  'LazySfIconVuejs': LazyComponent<typeof import("@storefront-ui/vue").SfIconVuejs>
  'LazySfIconVuestorefront': LazyComponent<typeof import("@storefront-ui/vue").SfIconVuestorefront>
  'LazySfIconWarehouse': LazyComponent<typeof import("@storefront-ui/vue").SfIconWarehouse>
  'LazySfIconWarning': LazyComponent<typeof import("@storefront-ui/vue").SfIconWarning>
  'LazySfIconYoutube': LazyComponent<typeof import("@storefront-ui/vue").SfIconYoutube>
  'LazySfInput': LazyComponent<typeof import("@storefront-ui/vue").SfInput>
  'LazySfLink': LazyComponent<typeof import("@storefront-ui/vue").SfLink>
  'LazySfListItem': LazyComponent<typeof import("@storefront-ui/vue").SfListItem>
  'LazySfLoaderCircular': LazyComponent<typeof import("@storefront-ui/vue").SfLoaderCircular>
  'LazySfLoaderLinear': LazyComponent<typeof import("@storefront-ui/vue").SfLoaderLinear>
  'LazySfModal': LazyComponent<typeof import("@storefront-ui/vue").SfModal>
  'LazySfProgressCircular': LazyComponent<typeof import("@storefront-ui/vue").SfProgressCircular>
  'LazySfProgressLinear': LazyComponent<typeof import("@storefront-ui/vue").SfProgressLinear>
  'LazySfRadio': LazyComponent<typeof import("@storefront-ui/vue").SfRadio>
  'LazySfRating': LazyComponent<typeof import("@storefront-ui/vue").SfRating>
  'LazySfRatingButton': LazyComponent<typeof import("@storefront-ui/vue").SfRatingButton>
  'LazySfScrollable': LazyComponent<typeof import("@storefront-ui/vue").SfScrollable>
  'LazySfSelect': LazyComponent<typeof import("@storefront-ui/vue").SfSelect>
  'LazySfSwitch': LazyComponent<typeof import("@storefront-ui/vue").SfSwitch>
  'LazySfTextarea': LazyComponent<typeof import("@storefront-ui/vue").SfTextarea>
  'LazySfThumbnail': LazyComponent<typeof import("@storefront-ui/vue").SfThumbnail>
  'LazySfTooltip': LazyComponent<typeof import("@storefront-ui/vue").SfTooltip>
  'LazyNuxtLinkLocale': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
  'LazySwitchLocalePathLink': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
  'LazyTiptapEditorContent': LazyComponent<typeof import("@tiptap/vue-3").EditorContent>
  'LazyTiptapFloatingMenu': LazyComponent<typeof import("@tiptap/vue-3/menus").FloatingMenu>
  'LazyTiptapBubbleMenu': LazyComponent<typeof import("@tiptap/vue-3/menus").BubbleMenu>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
