
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const ContentAddCategory: typeof import("../components/Content/add-category.vue").default
export const ContentAddTag: typeof import("../components/Content/add-tag.vue").default
export const ContentBlogDrafts: typeof import("../components/Content/blog/drafts.vue").default
export const ContentBlogPublished: typeof import("../components/Content/blog/published.vue").default
export const ContentCustomersAddAddresses: typeof import("../components/Content/customers/add-addresses.vue").default
export const ContentCustomersAddCalendar: typeof import("../components/Content/customers/add-calendar.vue").default
export const ContentCustomersAddCampaigns: typeof import("../components/Content/customers/add-campaigns.vue").default
export const ContentCustomersAddContracts: typeof import("../components/Content/customers/add-contracts.vue").default
export const ContentCustomersAddCustomers: typeof import("../components/Content/customers/add-customers.vue").default
export const ContentCustomersAddDocuments: typeof import("../components/Content/customers/add-documents.vue").default
export const ContentCustomersAddInvoice: typeof import("../components/Content/customers/add-invoice.vue").default
export const ContentCustomersAddLeads: typeof import("../components/Content/customers/add-leads.vue").default
export const ContentCustomersAddMeeting: typeof import("../components/Content/customers/add-meeting.vue").default
export const ContentCustomersAddOpportunities: typeof import("../components/Content/customers/add-opportunities.vue").default
export const ContentCustomersAddQuotes: typeof import("../components/Content/customers/add-quotes.vue").default
export const ContentCustomersAddSurveys: typeof import("../components/Content/customers/add-surveys.vue").default
export const ContentCustomersAddTargets: typeof import("../components/Content/customers/add-targets.vue").default
export const ContentCustomersAddVisits: typeof import("../components/Content/customers/add-visits.vue").default
export const EditorsEditor: typeof import("../components/Editors/editor.vue").default
export const FooterNav: typeof import("../components/FooterNav.vue").default
export const MenusCustomersmenu: typeof import("../components/Menus/customersmenu.vue").default
export const MenusListsmenu: typeof import("../components/Menus/listsmenu.vue").default
export const MenusMailmenu: typeof import("../components/Menus/mailmenu.vue").default
export const MenusMessengermenu: typeof import("../components/Menus/messengermenu.vue").default
export const MenusProjectsmenu: typeof import("../components/Menus/projectsmenu.vue").default
export const MenusTicketsmenu: typeof import("../components/Menus/ticketsmenu.vue").default
export const RelatedRelatedposts: typeof import("../components/Related/relatedposts.vue").default
export const RelatedRelatedproducts: typeof import("../components/Related/relatedproducts.vue").default
export const Search: typeof import("../components/Search/search.vue").default
export const Ecosystemmenu: typeof import("../components/ecosystemmenu.vue").default
export const HomePageBrowseteams: typeof import("../components/homePage/browseteams.vue").default
export const HomePageContentone: typeof import("../components/homePage/contentone.vue").default
export const HomePageContenttwo: typeof import("../components/homePage/contenttwo.vue").default
export const HomePageCreateteam: typeof import("../components/homePage/createteam.vue").default
export const HomePageLatest: typeof import("../components/homePage/latest.vue").default
export const HomePagePeople: typeof import("../components/homePage/people.vue").default
export const TheWelcome: typeof import("../../../node_modules/@sidebase/core/components/TheWelcome.vue").default
export const TheWelcomeContainer: typeof import("../../../node_modules/@sidebase/core/components/TheWelcomeContainer.vue").default
export const TimelineItem: typeof import("../../../node_modules/@sidebase/core/components/TimelineItem.vue").default
export const ContentDoc: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue").default
export const ContentList: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue").default
export const ContentNavigation: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue").default
export const ContentQuery: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue").default
export const ContentRenderer: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").default
export const ContentRendererMarkdown: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue").default
export const ContentSlot: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue").default
export const DocumentDrivenEmpty: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue").default
export const DocumentDrivenNotFound: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue").default
export const Markdown: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue").default
export const ProseCode: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue").default
export const ProseCodeInline: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue").default
export const ProsePre: typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue").default
export const ProseA: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue").default
export const ProseBlockquote: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue").default
export const ProseEm: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue").default
export const ProseH1: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue").default
export const ProseH2: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue").default
export const ProseH3: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue").default
export const ProseH4: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue").default
export const ProseH5: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue").default
export const ProseH6: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue").default
export const ProseHr: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue").default
export const ProseImg: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue").default
export const ProseLi: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue").default
export const ProseOl: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue").default
export const ProseP: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue").default
export const ProseScript: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue").default
export const ProseStrong: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue").default
export const ProseTable: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue").default
export const ProseTbody: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue").default
export const ProseTd: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue").default
export const ProseTh: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue").default
export const ProseThead: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue").default
export const ProseTr: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue").default
export const ProseUl: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue").default
export const NuxtWelcome: typeof import("../../../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../../../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../../../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
export const NuxtPicture: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
export const MDC: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").default
export const MDCRenderer: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").default
export const MDCSlot: typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").default
export const NuxtPage: typeof import("../../../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyContentAddCategory: LazyComponent<typeof import("../components/Content/add-category.vue").default>
export const LazyContentAddTag: LazyComponent<typeof import("../components/Content/add-tag.vue").default>
export const LazyContentBlogDrafts: LazyComponent<typeof import("../components/Content/blog/drafts.vue").default>
export const LazyContentBlogPublished: LazyComponent<typeof import("../components/Content/blog/published.vue").default>
export const LazyContentCustomersAddAddresses: LazyComponent<typeof import("../components/Content/customers/add-addresses.vue").default>
export const LazyContentCustomersAddCalendar: LazyComponent<typeof import("../components/Content/customers/add-calendar.vue").default>
export const LazyContentCustomersAddCampaigns: LazyComponent<typeof import("../components/Content/customers/add-campaigns.vue").default>
export const LazyContentCustomersAddContracts: LazyComponent<typeof import("../components/Content/customers/add-contracts.vue").default>
export const LazyContentCustomersAddCustomers: LazyComponent<typeof import("../components/Content/customers/add-customers.vue").default>
export const LazyContentCustomersAddDocuments: LazyComponent<typeof import("../components/Content/customers/add-documents.vue").default>
export const LazyContentCustomersAddInvoice: LazyComponent<typeof import("../components/Content/customers/add-invoice.vue").default>
export const LazyContentCustomersAddLeads: LazyComponent<typeof import("../components/Content/customers/add-leads.vue").default>
export const LazyContentCustomersAddMeeting: LazyComponent<typeof import("../components/Content/customers/add-meeting.vue").default>
export const LazyContentCustomersAddOpportunities: LazyComponent<typeof import("../components/Content/customers/add-opportunities.vue").default>
export const LazyContentCustomersAddQuotes: LazyComponent<typeof import("../components/Content/customers/add-quotes.vue").default>
export const LazyContentCustomersAddSurveys: LazyComponent<typeof import("../components/Content/customers/add-surveys.vue").default>
export const LazyContentCustomersAddTargets: LazyComponent<typeof import("../components/Content/customers/add-targets.vue").default>
export const LazyContentCustomersAddVisits: LazyComponent<typeof import("../components/Content/customers/add-visits.vue").default>
export const LazyEditorsEditor: LazyComponent<typeof import("../components/Editors/editor.vue").default>
export const LazyFooterNav: LazyComponent<typeof import("../components/FooterNav.vue").default>
export const LazyMenusCustomersmenu: LazyComponent<typeof import("../components/Menus/customersmenu.vue").default>
export const LazyMenusListsmenu: LazyComponent<typeof import("../components/Menus/listsmenu.vue").default>
export const LazyMenusMailmenu: LazyComponent<typeof import("../components/Menus/mailmenu.vue").default>
export const LazyMenusMessengermenu: LazyComponent<typeof import("../components/Menus/messengermenu.vue").default>
export const LazyMenusProjectsmenu: LazyComponent<typeof import("../components/Menus/projectsmenu.vue").default>
export const LazyMenusTicketsmenu: LazyComponent<typeof import("../components/Menus/ticketsmenu.vue").default>
export const LazyRelatedRelatedposts: LazyComponent<typeof import("../components/Related/relatedposts.vue").default>
export const LazyRelatedRelatedproducts: LazyComponent<typeof import("../components/Related/relatedproducts.vue").default>
export const LazySearch: LazyComponent<typeof import("../components/Search/search.vue").default>
export const LazyEcosystemmenu: LazyComponent<typeof import("../components/ecosystemmenu.vue").default>
export const LazyHomePageBrowseteams: LazyComponent<typeof import("../components/homePage/browseteams.vue").default>
export const LazyHomePageContentone: LazyComponent<typeof import("../components/homePage/contentone.vue").default>
export const LazyHomePageContenttwo: LazyComponent<typeof import("../components/homePage/contenttwo.vue").default>
export const LazyHomePageCreateteam: LazyComponent<typeof import("../components/homePage/createteam.vue").default>
export const LazyHomePageLatest: LazyComponent<typeof import("../components/homePage/latest.vue").default>
export const LazyHomePagePeople: LazyComponent<typeof import("../components/homePage/people.vue").default>
export const LazyTheWelcome: LazyComponent<typeof import("../../../node_modules/@sidebase/core/components/TheWelcome.vue").default>
export const LazyTheWelcomeContainer: LazyComponent<typeof import("../../../node_modules/@sidebase/core/components/TheWelcomeContainer.vue").default>
export const LazyTimelineItem: LazyComponent<typeof import("../../../node_modules/@sidebase/core/components/TimelineItem.vue").default>
export const LazyContentDoc: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue").default>
export const LazyContentList: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue").default>
export const LazyContentNavigation: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue").default>
export const LazyContentQuery: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue").default>
export const LazyContentRenderer: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").default>
export const LazyContentRendererMarkdown: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue").default>
export const LazyContentSlot: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue").default>
export const LazyDocumentDrivenEmpty: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue").default>
export const LazyDocumentDrivenNotFound: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue").default>
export const LazyMarkdown: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue").default>
export const LazyProseCode: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue").default>
export const LazyProseCodeInline: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue").default>
export const LazyProsePre: LazyComponent<typeof import("../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue").default>
export const LazyProseA: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue").default>
export const LazyProseBlockquote: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue").default>
export const LazyProseEm: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue").default>
export const LazyProseH1: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue").default>
export const LazyProseH2: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue").default>
export const LazyProseH3: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue").default>
export const LazyProseH4: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue").default>
export const LazyProseH5: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue").default>
export const LazyProseH6: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue").default>
export const LazyProseHr: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue").default>
export const LazyProseImg: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue").default>
export const LazyProseLi: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue").default>
export const LazyProseOl: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue").default>
export const LazyProseP: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue").default>
export const LazyProseScript: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue").default>
export const LazyProseStrong: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue").default>
export const LazyProseTable: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue").default>
export const LazyProseTbody: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue").default>
export const LazyProseTd: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue").default>
export const LazyProseTh: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue").default>
export const LazyProseThead: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue").default>
export const LazyProseTr: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue").default>
export const LazyProseUl: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
export const LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
export const LazyMDC: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").default>
export const LazyMDCRenderer: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").default>
export const LazyMDCSlot: LazyComponent<typeof import("../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").default>
export const LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
