<script setup lang="ts">
import { withDefaults } from 'vue'

const props = withDefaults(defineProps<{
  modelValue?: boolean
  label?: string
  autoGenerated?: boolean
}>(), {
  modelValue: false,
  label: '',
  autoGenerated: false,
})

const emit = defineEmits(['update:modelValue'])

const model = ref<boolean>(props.modelValue ?? false)

watch(model, (v) => emit('update:modelValue', v))
</script>

<template>
  <div style="display:flex;align-items:center;gap:8px">
    <v-switch
      v-model="model"
      :label="props.label || (model ? 'True' : 'False')"
      inset
      hide-details
    />
    <span v-if="props.autoGenerated" class="auto-badge">Auto</span>
  </div>
</template>

<style scoped>
.auto-badge{font-size:12px;padding:4px 6px;border-radius:4px;background:#eee;color:#333}
</style>