<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<{
    defaultValue?: string
    label?: string
    width?: string | null
    field: string
    required?: boolean
    options?: Record<string, any> | null
    modelValue?: string
    autoGenerated?: boolean
}>(), {
    required: false,
    options: null,
    width: null,
    autoGenerated: false,
})

const emit = defineEmits(['update:modelValue'])

const fieldWidth = props.width === 'full' ? '100%' : '50%'

const dateTimeValue = computed({
    get() {
        return props.modelValue || props.defaultValue || ''
    },
    set(value) {
        emit('update:modelValue', value)
    }
})
</script>

<template>
    <div :style="'width: ' + fieldWidth + '; display:flex; align-items:center; gap:8px'">
        <v-text-field :name="field" v-model="dateTimeValue" type="datetime-local" :required="required" :label="label" style="flex:1" />
        <span v-if="props.autoGenerated" class="auto-badge">Auto</span>
    </div>
</template>

<style scoped>
.auto-badge{font-size:12px;padding:4px 6px;border-radius:4px;background:#eee;color:#333}
input {width:100%;}
</style>
