<script setup lang="ts">
import { ref, computed } from 'vue'

const props = withDefaults(defineProps<{
    defaultValue?: string
    label?: string
    options?: Record<string, any> | null
    width?: string | null
    field: string
    required?: boolean
    modelValue?: any
    autoGenerated?: boolean
}>(), {
    required: false,
    options: null,
    width: null,
    autoGenerated: false,
})

const emit = defineEmits(['update:modelValue'])

const fieldWidth = props.width === 'full' ? '100%' : '50%'

const fileInput = ref(null)
const selectedFile = ref<File[] | null>(null)

const fileInputValue = computed({
    get() {
        return props.modelValue || props.defaultValue || null
    },
    set(value) {
        selectedFile.value = value
        
        // If we have a file, prepare it for upload
        if (value && value.length > 0) {
            const file = value[0]
            
            // Create FormData for file upload
            const formData = new FormData()
            formData.append('file', file)
            
            // Store the file object to be used during form submission
            emit('update:modelValue', {
                file: file,
                formData: formData,
                fileName: file.name,
                fileType: file.type,
                fileSize: file.size
            })
        } else {
            emit('update:modelValue', null)
        }
    }
})
</script>

<template>
    <div :style="'width: ' + fieldWidth + '; display:flex; align-items:center; gap:8px'">
        <v-file-input 
            ref="fileInput"
            clearable 
            density="compact" 
            :name="field" 
            v-model="fileInputValue" 
            :label="label" 
            :required="required"  
            variant="solo-inverted"
            accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt"
            prepend-icon="fas:fa fa-paperclip"
            :hint="selectedFile && selectedFile.length ? `${selectedFile.length} file(s) selected` : 'No file selected'"
            persistent-hint
        />
        <span v-if="props.autoGenerated" class="auto-badge">Auto</span>
    </div>
</template>

<style scoped>
input {
    width: 100%;
}
</style>

<style scoped>
.auto-badge{font-size:12px;padding:4px 6px;border-radius:4px;background:#eee;color:#333}
</style>
