<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import DirectusFormElement from './DirectusFormElement.vue'

const props = withDefaults(defineProps<{
  modelValue?: any
  field: string
  label?: string
  options?: Record<string, any>
  required?: boolean
  width?: string | null
  autoGenerated?: boolean
}>(), {
  options: () => ({} as Record<string, any>),
  label: '',
  required: false,
  width: null,
  autoGenerated: false,
})

const emit = defineEmits(['update:modelValue'])

const items = ref<Array<any>>(Array.isArray(props.modelValue) ? JSON.parse(JSON.stringify(props.modelValue)) : [])
const jsonMode = ref(false)

watch(() => props.modelValue, (v) => {
  items.value = Array.isArray(v) ? JSON.parse(JSON.stringify(v)) : []
})

const createEmptyItem = () => {
  const fields = (props.options && Array.isArray(props.options.fields)) ? props.options.fields : null
  if (!fields) return ''
  const obj: Record<string, any> = {}
  for (const f of fields) {
    obj[f.field] = f.schema?.default_value ?? ''
  }
  return obj
}

const addItem = () => {
  items.value.push(createEmptyItem())
  emit('update:modelValue', items.value)
}

const removeItem = (idx: number) => {
  items.value.splice(idx, 1)
  emit('update:modelValue', items.value)
}

const updateItem = (idx: number, val: any) => {
  items.value[idx] = val
  emit('update:modelValue', items.value)
}

const toggleJson = () => {
  jsonMode.value = !jsonMode.value
}

/**
 * Handle textarea input for JSON mode in script (typed), avoiding template typing issues.
 */
const onJsonInput = (e: Event) => {
  const target = e.target as HTMLTextAreaElement | null
  if (!target) return
  const text = target.value
  try {
    const parsed = JSON.parse(text)
    emit('update:modelValue', parsed)
    items.value = Array.isArray(parsed) ? parsed : []
  } catch (err) {
    // ignore invalid json until saved
  }
}
</script>

<template>
  <div :style="'width: ' + (props.width === 'full' ? '100%' : '50%')">
    <label style="display:flex;align-items:center;justify-content:space-between;margin-bottom:6px">
      <span>{{ props.label || props.field }}</span>
      <button type="button" @click="toggleJson" style="font-size:12px">{{ jsonMode ? 'Edit Items' : 'Edit JSON' }}</button>
    </label>

    <div v-if="!jsonMode">
      <div v-for="(it, idx) in items" :key="idx" style="border:1px solid #eee;padding:8px;margin-bottom:8px">
        <div style="display:flex;flex-direction:column;gap:8px">
          <template v-if="props.options && Array.isArray(props.options.fields) && props.options.fields.length">
            <DirectusFormElement
              v-for="sub in props.options.fields"
              :key="sub.field"
              :field="sub"
              v-model="items[idx][sub.field]"
            />
          </template>
          <template v-else>
            <div style="display:flex;gap:8px;align-items:center;margin-bottom:6px">
              <input type="text" v-model="items[idx]" @input="updateItem(idx, items[idx])" style="flex:1;padding:8px" />
            </div>
          </template>
        </div>

        <div style="display:flex;justify-content:flex-end;margin-top:8px">
          <button type="button" @click="removeItem(idx)" style="padding:6px">Remove</button>
        </div>
      </div>

      <button type="button" @click="addItem" style="padding:6px">Add item</button>
    </div>

    <div v-else>
      <textarea
        style="width:100%;min-height:200px;padding:8px"
        :value="JSON.stringify(items, null, 2)"
        @input="onJsonInput"
      ></textarea>
    </div>
  </div>
</template>

<style scoped>
button{cursor:pointer}
</style>
