<template>
    <div :style="'width: ' + fieldWidth + '; display:flex; align-items:flex-start; gap:8px'">
        <client-only>
            <tiptap-editor :name="field" v-model="textAreaValue" rows="12" :required="required" :label="label" style="flex:1" />
        </client-only>
        <span v-if="props.autoGenerated" class="auto-badge">Auto</span>
    </div>
</template>

<script setup lang="ts">
    import {
        computed
    } from 'vue'
    import TiptapEditor from './TiptapEditor.vue'

    const props = withDefaults(defineProps < {
        defaultValue ? : string
        label ? : string
        width ? : string | null
        field: string
        required ? : boolean
        options ? : Record < string,
        any > | null
        modelValue ? : string
        autoGenerated ? : boolean
    } > (), {
        required: false,
        options: null,
        width: null,
        autoGenerated: false,
    })

    const emit = defineEmits(['update:modelValue'])

    const fieldWidth = props.width === 'full' ? '100%' : '50%'

    const textAreaValue = computed({
        get() {
            return props.modelValue || props.defaultValue || ''
        },
        set(value) {
            emit('update:modelValue', value)
        }
    })
</script>

<style scoped>
    .auto-badge {
        font-size: 12px;
        padding: 4px 6px;
        border-radius: 4px;
        background: #eee;
        color: #333
    }

    textarea {
        width: 100%
    }
</style>