
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'BottomFooter': typeof import("../../components/BottomFooter.vue").default
  'CatbarLive': typeof import("../../components/Catbar/live.vue").default
  'CommerceBillingaddress': typeof import("../../components/Commerce/billingaddress.vue").default
  'CommerceShippingaddress': typeof import("../../components/Commerce/shippingaddress.vue").default
  'CreateCreatelist': typeof import("../../components/Create/createlist.vue").default
  'CreateCreatelive': typeof import("../../components/Create/createlive.vue").default
  'CreateProduct': typeof import("../../components/Create/product.vue").default
  'CreateVideo': typeof import("../../components/Create/video.vue").default
  'CreatorsRelatedauthors': typeof import("../../components/Creators/relatedauthors.vue").default
  'CreatorsRelatedcreators': typeof import("../../components/Creators/relatedcreators.vue").default
  'CreatorsRelateddevelopers': typeof import("../../components/Creators/relateddevelopers.vue").default
  'EditorsEditor': typeof import("../../components/Editors/editor.vue").default
  'FooterNav': typeof import("../../components/FooterNav.vue").default
  'MenusTopMenuTopaccountmenu': typeof import("../../components/Menus/TopMenu/topaccountmenu.vue").default
  'MenusAccountmenu': typeof import("../../components/Menus/accountmenu.vue").default
  'MenusCategoriesmenu': typeof import("../../components/Menus/categoriesmenu.vue").default
  'MenusDealsmenu': typeof import("../../components/Menus/dealsmenu.vue").default
  'MenusDepartmentsmenu': typeof import("../../components/Menus/departmentsmenu.vue").default
  'MenusEcosystemmenu': typeof import("../../components/Menus/ecosystemmenu.vue").default
  'MenusExploremenu': typeof import("../../components/Menus/exploremenu.vue").default
  'MenusProfilebar': typeof import("../../components/Menus/profilebar.vue").default
  'ProductRelatedsidebar': typeof import("../../components/Product/relatedsidebar.vue").default
  'ProfileFollowers': typeof import("../../components/Profile/followers.vue").default
  'ProfileFollowing': typeof import("../../components/Profile/following.vue").default
  'ProfileLikes': typeof import("../../components/Profile/likes.vue").default
  'ProfileMedia': typeof import("../../components/Profile/media.vue").default
  'ProfileProducts': typeof import("../../components/Profile/products.vue").default
  'ProfileReplies': typeof import("../../components/Profile/replies.vue").default
  'RelatedBestsellers': typeof import("../../components/Related/bestsellers.vue").default
  'RelatedFeaturedproducts': typeof import("../../components/Related/featuredproducts.vue").default
  'RelatedLatestproducts': typeof import("../../components/Related/latestproducts.vue").default
  'RelatedRecentlyviewed': typeof import("../../components/Related/recentlyviewed.vue").default
  'RelatedRelatedcategories': typeof import("../../components/Related/relatedcategories.vue").default
  'RelatedRelatedgallery': typeof import("../../components/Related/relatedgallery.vue").default
  'RelatedRelatedposts': typeof import("../../components/Related/relatedposts.vue").default
  'RelatedRelatedproducts': typeof import("../../components/Related/relatedproducts.vue").default
  'RelatedRelatedvideo': typeof import("../../components/Related/relatedvideo.vue").default
  'Search': typeof import("../../components/Search/search.vue").default
  'VideoVideojs': typeof import("../../components/Video/videojs.vue").default
  'UserProfilesubpage': typeof import("../../components/user/profilesubpage.vue").default
  'TheWelcome': typeof import("../../../../node_modules/@sidebase/core/components/TheWelcome.vue").default
  'TheWelcomeContainer': typeof import("../../../../node_modules/@sidebase/core/components/TheWelcomeContainer.vue").default
  'TimelineItem': typeof import("../../../../node_modules/@sidebase/core/components/TimelineItem.vue").default
  'ContentDoc': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue").default
  'ContentList': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue").default
  'ContentNavigation': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue").default
  'ContentQuery': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue").default
  'ContentRenderer': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").default
  'ContentRendererMarkdown': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue").default
  'ContentSlot': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue").default
  'DocumentDrivenEmpty': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue").default
  'DocumentDrivenNotFound': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue").default
  'Markdown': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue").default
  'ProseCode': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue").default
  'ProseCodeInline': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue").default
  'ProsePre': typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue").default
  'ProseA': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue").default
  'ProseBlockquote': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue").default
  'ProseEm': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue").default
  'ProseH1': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue").default
  'ProseH2': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue").default
  'ProseH3': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue").default
  'ProseH4': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue").default
  'ProseH5': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue").default
  'ProseH6': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue").default
  'ProseHr': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue").default
  'ProseImg': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue").default
  'ProseLi': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue").default
  'ProseOl': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue").default
  'ProseP': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue").default
  'ProseScript': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue").default
  'ProseStrong': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue").default
  'ProseTable': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue").default
  'ProseTbody': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue").default
  'ProseTd': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue").default
  'ProseTh': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue").default
  'ProseThead': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue").default
  'ProseTr': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue").default
  'ProseUl': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue").default
  'NuxtWelcome': typeof import("../../../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
  'NuxtPicture': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
  'MDC': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").default
  'MDCRenderer': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").default
  'MDCSlot': typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").default
  'NuxtPage': typeof import("../../../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyBottomFooter': LazyComponent<typeof import("../../components/BottomFooter.vue").default>
  'LazyCatbarLive': LazyComponent<typeof import("../../components/Catbar/live.vue").default>
  'LazyCommerceBillingaddress': LazyComponent<typeof import("../../components/Commerce/billingaddress.vue").default>
  'LazyCommerceShippingaddress': LazyComponent<typeof import("../../components/Commerce/shippingaddress.vue").default>
  'LazyCreateCreatelist': LazyComponent<typeof import("../../components/Create/createlist.vue").default>
  'LazyCreateCreatelive': LazyComponent<typeof import("../../components/Create/createlive.vue").default>
  'LazyCreateProduct': LazyComponent<typeof import("../../components/Create/product.vue").default>
  'LazyCreateVideo': LazyComponent<typeof import("../../components/Create/video.vue").default>
  'LazyCreatorsRelatedauthors': LazyComponent<typeof import("../../components/Creators/relatedauthors.vue").default>
  'LazyCreatorsRelatedcreators': LazyComponent<typeof import("../../components/Creators/relatedcreators.vue").default>
  'LazyCreatorsRelateddevelopers': LazyComponent<typeof import("../../components/Creators/relateddevelopers.vue").default>
  'LazyEditorsEditor': LazyComponent<typeof import("../../components/Editors/editor.vue").default>
  'LazyFooterNav': LazyComponent<typeof import("../../components/FooterNav.vue").default>
  'LazyMenusTopMenuTopaccountmenu': LazyComponent<typeof import("../../components/Menus/TopMenu/topaccountmenu.vue").default>
  'LazyMenusAccountmenu': LazyComponent<typeof import("../../components/Menus/accountmenu.vue").default>
  'LazyMenusCategoriesmenu': LazyComponent<typeof import("../../components/Menus/categoriesmenu.vue").default>
  'LazyMenusDealsmenu': LazyComponent<typeof import("../../components/Menus/dealsmenu.vue").default>
  'LazyMenusDepartmentsmenu': LazyComponent<typeof import("../../components/Menus/departmentsmenu.vue").default>
  'LazyMenusEcosystemmenu': LazyComponent<typeof import("../../components/Menus/ecosystemmenu.vue").default>
  'LazyMenusExploremenu': LazyComponent<typeof import("../../components/Menus/exploremenu.vue").default>
  'LazyMenusProfilebar': LazyComponent<typeof import("../../components/Menus/profilebar.vue").default>
  'LazyProductRelatedsidebar': LazyComponent<typeof import("../../components/Product/relatedsidebar.vue").default>
  'LazyProfileFollowers': LazyComponent<typeof import("../../components/Profile/followers.vue").default>
  'LazyProfileFollowing': LazyComponent<typeof import("../../components/Profile/following.vue").default>
  'LazyProfileLikes': LazyComponent<typeof import("../../components/Profile/likes.vue").default>
  'LazyProfileMedia': LazyComponent<typeof import("../../components/Profile/media.vue").default>
  'LazyProfileProducts': LazyComponent<typeof import("../../components/Profile/products.vue").default>
  'LazyProfileReplies': LazyComponent<typeof import("../../components/Profile/replies.vue").default>
  'LazyRelatedBestsellers': LazyComponent<typeof import("../../components/Related/bestsellers.vue").default>
  'LazyRelatedFeaturedproducts': LazyComponent<typeof import("../../components/Related/featuredproducts.vue").default>
  'LazyRelatedLatestproducts': LazyComponent<typeof import("../../components/Related/latestproducts.vue").default>
  'LazyRelatedRecentlyviewed': LazyComponent<typeof import("../../components/Related/recentlyviewed.vue").default>
  'LazyRelatedRelatedcategories': LazyComponent<typeof import("../../components/Related/relatedcategories.vue").default>
  'LazyRelatedRelatedgallery': LazyComponent<typeof import("../../components/Related/relatedgallery.vue").default>
  'LazyRelatedRelatedposts': LazyComponent<typeof import("../../components/Related/relatedposts.vue").default>
  'LazyRelatedRelatedproducts': LazyComponent<typeof import("../../components/Related/relatedproducts.vue").default>
  'LazyRelatedRelatedvideo': LazyComponent<typeof import("../../components/Related/relatedvideo.vue").default>
  'LazySearch': LazyComponent<typeof import("../../components/Search/search.vue").default>
  'LazyVideoVideojs': LazyComponent<typeof import("../../components/Video/videojs.vue").default>
  'LazyUserProfilesubpage': LazyComponent<typeof import("../../components/user/profilesubpage.vue").default>
  'LazyTheWelcome': LazyComponent<typeof import("../../../../node_modules/@sidebase/core/components/TheWelcome.vue").default>
  'LazyTheWelcomeContainer': LazyComponent<typeof import("../../../../node_modules/@sidebase/core/components/TheWelcomeContainer.vue").default>
  'LazyTimelineItem': LazyComponent<typeof import("../../../../node_modules/@sidebase/core/components/TimelineItem.vue").default>
  'LazyContentDoc': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue").default>
  'LazyContentList': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue").default>
  'LazyContentNavigation': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue").default>
  'LazyContentQuery': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue").default>
  'LazyContentRenderer': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").default>
  'LazyContentRendererMarkdown': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue").default>
  'LazyContentSlot': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue").default>
  'LazyDocumentDrivenEmpty': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue").default>
  'LazyDocumentDrivenNotFound': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue").default>
  'LazyMarkdown': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue").default>
  'LazyProseCode': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue").default>
  'LazyProseCodeInline': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue").default>
  'LazyProsePre': LazyComponent<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue").default>
  'LazyProseA': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue").default>
  'LazyProseBlockquote': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue").default>
  'LazyProseEm': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue").default>
  'LazyProseH1': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue").default>
  'LazyProseH2': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue").default>
  'LazyProseH3': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue").default>
  'LazyProseH4': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue").default>
  'LazyProseH5': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue").default>
  'LazyProseH6': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue").default>
  'LazyProseHr': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue").default>
  'LazyProseImg': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue").default>
  'LazyProseLi': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue").default>
  'LazyProseOl': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue").default>
  'LazyProseP': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue").default>
  'LazyProseScript': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue").default>
  'LazyProseStrong': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue").default>
  'LazyProseTable': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue").default>
  'LazyProseTbody': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue").default>
  'LazyProseTd': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue").default>
  'LazyProseTh': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue").default>
  'LazyProseThead': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue").default>
  'LazyProseTr': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue").default>
  'LazyProseUl': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
  'LazyNuxtPicture': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
  'LazyMDC': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").default>
  'LazyMDCRenderer': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").default>
  'LazyMDCSlot': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
