// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/18/2026, 9:23:25 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/plugins/**/*.{js,ts,mjs}","/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/composables/**/*.{js,ts,mjs}","/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/utils/**/*.{js,ts,mjs}","/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/meebuzo/github/meeovi/apps/Meeovi-Starter-Template/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;