query getStripeConfiguration{
    getStripeConfiguration{
        apiKey
        appInfo
        elementsOptions
        locale
        options{
            apiVersion
            betas
        }
    }
}